require 'rails_helper'
# Если BetForm находится в папке app/forms, то он должен быть доступен
# через rails_helper или auto-require. Если нет, добавьте require 'app/forms/bet_form'

RSpec.describe BetForm, type: :model do
  # --- ХЕЛПЕР: Набор валидных атрибутов ---
  let(:valid_attributes) do
    {
      user_id: 123,
      amount: 10.50,
      auto_cashout: 2.00,
      client_seed: 'supersecureseed',
      session_token: 'valid_session_token'
    }
  end

  subject(:form) { described_class.new(attributes) }

  # =========================================================
  # 1. ТЕСТ: Базовая Валидация (Все поля корректны)
  # =========================================================
  context 'when all attributes are valid' do
    let(:attributes) { valid_attributes }
    it { is_expected.to be_valid }

    it 'is valid when auto_cashout is nil (allow_nil: true)' do
      attributes = valid_attributes.except(:auto_cashout)
      expect(described_class.new(attributes)).to be_valid
    end
  end

  # =========================================================
  # 2. ТЕСТ: user_id
  # =========================================================
  describe 'user_id validation' do
    context 'when user_id is missing' do
      let(:attributes) { valid_attributes.merge(user_id: nil) }
      it { is_expected.to be_invalid }
      it 'adds an error message' do
        form.valid?
        expect(form.errors[:user_id]).to include("can't be blank")
      end
    end
  end

  # =========================================================
  # 3. ТЕСТ: amount
  # =========================================================
  describe 'amount validation' do
    context 'when amount is missing' do
      let(:attributes) { valid_attributes.merge(amount: nil) }
      it { is_expected.to be_invalid }
      it 'adds can\'t be blank error' do
        form.valid?
        expect(form.errors[:amount]).to include("can't be blank")
      end
    end

    context 'when amount is zero or negative' do
      let(:attributes) { valid_attributes.merge(amount: 0.0) }
      it { is_expected.to be_invalid }
      it 'adds greater than 0.0 error' do
        form.valid?
        expect(form.errors[:amount]).to include('must be greater than 0.0')
      end
    end

    context 'when amount is too large' do
      let(:attributes) { valid_attributes.merge(amount: 1_000_000.01) }
      it { is_expected.to be_invalid }
      it 'adds less than or equal to error' do
        form.valid?
        expect(form.errors[:amount]).to include('must be less than or equal to 1000000.0')
      end
    end
  end

  # =========================================================
  # 4. ТЕСТ: auto_cashout
  # =========================================================
  describe 'auto_cashout validation' do
    context 'when auto_cashout is less than 1.0' do
      let(:attributes) { valid_attributes.merge(auto_cashout: 0.99) }
      it { is_expected.to be_invalid }
      it 'adds greater than or equal to 1.0 error' do
        form.valid?
        expect(form.errors[:auto_cashout]).to include('must be greater than or equal to 1.0')
      end
    end

    context 'when auto_cashout is a string' do
      let(:attributes) { valid_attributes.merge(auto_cashout: 'abc') }
      it { is_expected.to be_invalid }
      # FIX: Changing the expectation to match the actual error generated by Rails
      # when a non-numeric string is cast to a :decimal (resulting in 0.0)
      it 'adds the range error because the string typecasts to a value less than 1.0' do
        form.valid?
        expect(form.errors[:auto_cashout]).to include('must be greater than or equal to 1.0')
      end
    end

    # Тест allow_nil: true
    context 'when auto_cashout is omitted (nil)' do
      let(:attributes) { valid_attributes.except(:auto_cashout) }
      it { is_expected.to be_valid }
    end
  end

  # =========================================================
  # 5. ТЕСТ: client_seed
  # =========================================================
  describe 'client_seed validation' do
    context 'when client_seed is missing' do
      let(:attributes) { valid_attributes.merge(client_seed: nil) }
      it { is_expected.to be_invalid }
      it 'adds can\'t be blank error' do
        form.valid?
        expect(form.errors[:client_seed]).to include("can't be blank")
      end
    end

    context 'when client_seed is too short (less than 5 chars)' do
      let(:attributes) { valid_attributes.merge(client_seed: 'abcd') }
      it { is_expected.to be_invalid }
      it 'adds is too short error' do
        form.valid?
        expect(form.errors[:client_seed]).to include('is too short (minimum is 5 characters)')
      end
    end

    context 'when client_seed is exactly 5 characters' do
      let(:attributes) { valid_attributes.merge(client_seed: 'abcde') }
      it { is_expected.to be_valid }
    end
  end
end
